### ISSUE TITLE
It is working with OpenStack Newton?

### ISSUE THREAD

**Issue by manuparra** [ispras/spark-openstack#11]
It is working with OpenStack Newton?

**Comment by al-indigo** [comment]
@manuparra It should since we use universal drivers. But we didn't test it on Newton yet - you are welcome to report the results

**Comment by manuparra** [comment]
Okay perfect! I will try!

**Comment by al-indigo** [comment]
@manuparra did it succeed?

**Comment by manuparra** [comment]
Hello Oleg, my team will try it this week.

I have another question. Comparing OpenStack Sahara and your scripts, do
you think that if we only need deploy spark+etc will get the same results?
I would like to update your solution and to add a new set of "clusters"
like R cluster, MPI, etc.


Regards.

**Comment by al-indigo** [comment]
@manuparra Hello. Actually we took part in Spark jobs implementation in Sahara :) so I can tell you pretty sure the following:

1) Sahara supports different variations for embedded tools. Particularly Spark may be as Cloudera distribution, HortonWorks distribution, MapR distribution and Vanilla. Vanilla version doesn't integrate with other big data tools. The others differ slightly in folders locations, web-management and all of them work in YARN mode only (as far as I remember).
2) Our scripts "complement" Sahara to be used by developers using Spark/Scala. Sahara is more oriented on end-users - it's rather difficult to debug programs if they are run inside Sahara environment.
3) Our scripts contain much less tools but they are much more flexible: you can use any tool of any version and they are easy to extend. Sahara is hard-locked on specific versions and has half-a-year release cycle so you will be always limited to the Spark version issued on Openstack release date.

Nevertheless the results of Spark performance/Spark behaviour are totally the same.

**Comment by manuparra** [comment]
Hello again ! thanks ! your responses are very clear.
Well, we've re-installed OpenStack RDO and everything are working (MVs, network, cinder, horizon, etc.). But when we use your script I want to report an issues; it's happening the next:

> 
> [WARNING]: provided hosts list is empty, only localhost is available
> Traceback (most recent call last):
>   File "./openstack_inventory.py", line 55, in <module>
>     import shade
> ImportError: No module named shade
> ERROR! The file openstack_inventory.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x openstack_inventory.py`.
> Inventory script (openstack_inventory.py) had an execution error: Traceback (most recent call last):
>   File "/root/spark-openstack-master/ansible/openstack_inventory.py", line 55, in <module>
>     import shade
> ImportError: No module named shade


Well I know that this error can be solved installing python shade library, but Id like to know if I must install more libraries or an additional openstack package . In your tutorial of installation only a few packages are installed, but not shade, for instance.  Could you update your installation tutorial? or this is an issue on own openstack installation?

**Comment by al-indigo** [comment]
I see that you have deleted a comment, but to be clear I'll point the
following out (hope you see notifications in email because I will delete
the answer too). There are the following client-side requirements:
1) System packages: libffi-dev libssl-dev python-dev
2) Python packages: pip six ansible shade

There is no need in additional Openstack components

We tell about it in the first chapter of README.md
