### ISSUE TITLE
checkpoints in swift

### ISSUE THREAD

**Issue by mazorigal** [ispras/spark-openstack#13]
Hi,

is it possible to use swift storage for spark checkpoints ?
(especially if I dont need spark with hadoop)

Thanks,

**Comment by al-indigo** [comment]
I suppose it's possible and you can use it right now using this project. 
It's done the same way you do it with hdfs ("reliable checkpoints" in Spark docs) but you need to specify correct Swift path in your `SparkContext.setCheckpointDir(directory: String)` and that's all.

**Comment by al-indigo** [comment]
But keep in mind that to make Swift work with Spark you really _need_ Spark with Hadoop: Swift integration doesn't work without Hadoop core. You just shouldn't use the default HDFS if you don't want to -- you will have no performance issues if you just ignore that HDFS is running in the system.
