### ISSUE TITLE
hdfs storage

### ISSUE THREAD

**Issue by apurvann** [ispras/spark-openstack#16]
Is the HDFS designed to work by default when one deploys the cluster using the playbooks, or do we need to configure something else. 

When I do : 
`hdfs dfsadmin -report`

I see there are 0 datanodes running. I tried to format the namenode to no avail. 

Looking at the logs, it looked like a connection problem to the master, even though the ports seem to be opened.

**Comment by al-indigo** [comment]
Did you specify your floating IP pool address?
Did the script successfully finished its work?
Also check please the contents of /etc/hosts on all the nodes: we you it on purpose to go through virtual network without DNS queries — it can be the problem too.
