### ISSUE TITLE
Working with a highly limited Floating IP Pool

### ISSUE THREAD

**Issue by frehage** [ispras/spark-openstack#20]
Hej!

I have a highly restricted Floating IP Pool to my disposal.

Is it possible to set the cluster up such that the master has a floating IP and can be accessed from outside while all internal communication is handled via a local private network? 

I am a new to both OpenStack and spark so maybe this is a stupid question...

Thank you!
Fredrik

**Comment by al-indigo** [comment]
We can do it rather easily in the following way:
1. You should create a VM with one floating IP, copy your ssh credentials and ..-openrc.sh file,  and clone this repository to it (with all prerequisites). Let's call it management VM.
2. From this management VM you may create a cluster with option `-f None`.
3. After cluster creation you can assign floating IP to master instance manually and everything should work. If you have only one floating IP available, you can detach it from "management VM" and reassign it to spark master instance.

"None" behaviour is not implemented for now, but it's rather easy, stay tuned to this issue.

**Comment by al-indigo** [comment]
@lazarevnik do it please. The behaviour should be the following:
1) If `-f None` specified, you should use private network IPs instead of public.
2) Don't forget to check this option in create/create_async scenarios.

**Comment by frehage** [comment]
thanks a lot! I think that this can be a nice feature. tracking this issue with interest!

**Comment by lazarevnik** [comment]
Hi!
[Pull request](https://github.com/ispras/spark-openstack/pull/21#issue-302949551) with this functionality is ready.
[Readme](https://github.com/ispras/spark-openstack/blob/master/README.md) contains instructions. In short, it works as described above:
- Created VM with floating ip and this project
- Than you can use it to do cluster without `-f` option.

@al-indigo check this please.

**Comment by al-indigo** [comment]
@frehage You can try it. If something is wrong, please reopen the issue
